apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 2         # <-- 기존 1에서 2로 수정
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - image: nginx
        name: mynginx
        ports:
        - containerPort: 80
